/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-9-8: 21h:45m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
typedef
ATSstruct {
atstkind_t0ype(atstype_int) atslab__0 ;
atstkind_t0ype(atstype_int) atslab__1 ;
atstkind_t0ype(atstype_int) atslab__2 ;
atstkind_t0ype(atstype_int) atslab__3 ;
atstkind_t0ype(atstype_int) atslab__4 ;
atstkind_t0ype(atstype_int) atslab__5 ;
atstkind_t0ype(atstype_int) atslab__6 ;
atstkind_t0ype(atstype_int) atslab__7 ;
} postiats_tyrec_0 ;
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_print_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
ATSstatic()
atsvoid_t0ype
print_dots_0(atstkind_t0ype(atstype_int)) ;

ATSstatic()
atsvoid_t0ype
print_row_1(atstkind_t0ype(atstype_int)) ;

ATSstatic()
atsvoid_t0ype
print_board_2(postiats_tyrec_0) ;

ATSstatic()
atstkind_t0ype(atstype_int)
board_get_3(postiats_tyrec_0, atstkind_t0ype(atstype_int)) ;

ATSstatic()
postiats_tyrec_0
board_set_4(postiats_tyrec_0, atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
safety_test1_5(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_bool)
safety_test2_6(atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), postiats_tyrec_0, atstkind_t0ype(atstype_int)) ;

ATSstatic()
atstkind_t0ype(atstype_int)
search_7(postiats_tyrec_0, atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int), atstkind_t0ype(atstype_int)) ;

#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 79(line=8, offs=5) -- 161(line=9, offs=55)
*/
/*
local: print_dots_0$0(level=0)
global: print_dots_0$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
print_dots_0(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmpret0) ;
ATStmpdec(tmp1, atstkind_t0ype(atstype_bool)) ;
// ATStmpdec_void(tmp2) ;
ATStmpdec(tmp3, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 79(line=8, offs=5) -- 161(line=9, offs=55)
*/
ATSINSflab(__patsflab_print_dots_0):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 112(line=9, offs=6) -- 117(line=9, offs=11)
*/
ATSINSmove(tmp1, PMVtmpltcstmat[0](gt_g0int_int<S2Eextkind(atstype_int)>)(arg0, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 109(line=9, offs=3) -- 161(line=9, offs=55)
*/
ATSif(
tmp1
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 124(line=9, offs=18) -- 134(line=9, offs=28)
*/
ATSINSmove_void(tmp2, atspre_print_string(ATSPMVstring(". "))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 148(line=9, offs=42) -- 151(line=9, offs=45)
*/
ATSINSmove(tmp3, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg0, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 136(line=9, offs=30) -- 152(line=9, offs=46)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSfgoto(__patsflab_print_dots_0) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 159(line=9, offs=53) -- 161(line=9, offs=55)
*/
ATSINSmove_void(tmpret0, ATSPMVempty()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [print_dots_0] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 167(line=11, offs=5) -- 259(line=14, offs=2)
*/
/*
local: print_dots_0$0(level=0)
global: print_dots_0$0(level=0), print_row_1$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
print_row_1(atstkind_t0ype(atstype_int) arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret4) ;
// ATStmpdec_void(tmp5) ;
// ATStmpdec_void(tmp6) ;
// ATStmpdec_void(tmp7) ;
ATStmpdec(tmp8, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp9, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 167(line=11, offs=5) -- 259(line=14, offs=2)
*/
ATSINSflab(__patsflab_print_row_1):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 198(line=13, offs=3) -- 211(line=13, offs=16)
*/
ATSINSmove_void(tmp5, print_dots_0(arg0)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 214(line=13, offs=19) -- 224(line=13, offs=29)
*/
ATSINSmove_void(tmp6, atspre_print_string(ATSPMVstring("Q "))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 238(line=13, offs=43) -- 241(line=13, offs=46)
*/
ATSINSmove(tmp9, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(ATSPMVintrep(8), arg0)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 238(line=13, offs=43) -- 243(line=13, offs=48)
*/
ATSINSmove(tmp8, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(tmp9, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 226(line=13, offs=31) -- 244(line=13, offs=49)
*/
ATSINSmove_void(tmp7, print_dots_0(tmp8)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 246(line=13, offs=51) -- 256(line=13, offs=61)
*/
ATSINSmove_void(tmpret4, atspre_print_string(ATSPMVstring("\n"))) ;

ATSfunbody_end()
ATSreturn_void(tmpret4) ;
} /* end of [print_row_1] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 265(line=16, offs=5) -- 466(line=21, offs=2)
*/
/*
local: print_row_1$0(level=0)
global: print_dots_0$0(level=0), print_row_1$0(level=0), print_board_2$0(level=0)
local: 
global: 
*/
ATSstatic()
atsvoid_t0ype
print_board_2(postiats_tyrec_0 arg0)
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret10) ;
// ATStmpdec_void(tmp11) ;
// ATStmpdec_void(tmp12) ;
// ATStmpdec_void(tmp13) ;
// ATStmpdec_void(tmp14) ;
// ATStmpdec_void(tmp15) ;
// ATStmpdec_void(tmp16) ;
// ATStmpdec_void(tmp17) ;
// ATStmpdec_void(tmp18) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 265(line=16, offs=5) -- 466(line=21, offs=2)
*/
ATSINSflab(__patsflab_print_board_2):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 300(line=18, offs=3) -- 316(line=18, offs=19)
*/
ATSINSmove_void(tmp11, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 318(line=18, offs=21) -- 334(line=18, offs=37)
*/
ATSINSmove_void(tmp12, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 336(line=18, offs=39) -- 352(line=18, offs=55)
*/
ATSINSmove_void(tmp13, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__2))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 354(line=18, offs=57) -- 370(line=18, offs=73)
*/
ATSINSmove_void(tmp14, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__3))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 374(line=19, offs=3) -- 390(line=19, offs=19)
*/
ATSINSmove_void(tmp15, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__4))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 392(line=19, offs=21) -- 408(line=19, offs=37)
*/
ATSINSmove_void(tmp16, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__5))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 410(line=19, offs=39) -- 426(line=19, offs=55)
*/
ATSINSmove_void(tmp17, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__6))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 428(line=19, offs=57) -- 444(line=19, offs=73)
*/
ATSINSmove_void(tmp18, print_row_1(ATSSELfltrec(arg0, postiats_tyrec_0, atslab__7))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 448(line=20, offs=3) -- 464(line=20, offs=19)
*/
ATSINSmove_void(tmpret10, atspre_print_newline()) ;

ATSfunbody_end()
ATSreturn_void(tmpret10) ;
} /* end of [print_board_2] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 472(line=23, offs=5) -- 722(line=33, offs=10)
*/
/*
local: 
global: board_get_3$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
board_get_3(postiats_tyrec_0 arg0, atstkind_t0ype(atstype_int) arg1)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret19, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp20, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp21, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp22, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp23, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp24, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp25, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp26, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp27, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 472(line=23, offs=5) -- 722(line=33, offs=10)
*/
ATSINSflab(__patsflab_board_get_3):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 515(line=25, offs=6) -- 520(line=25, offs=11)
*/
ATSINSmove(tmp20, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 512(line=25, offs=3) -- 722(line=33, offs=10)
*/
ATSif(
tmp20
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 526(line=25, offs=17) -- 530(line=25, offs=21)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 541(line=26, offs=11) -- 546(line=26, offs=16)
*/
ATSINSmove(tmp21, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 538(line=26, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp21
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 552(line=26, offs=22) -- 556(line=26, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__1)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 567(line=27, offs=11) -- 572(line=27, offs=16)
*/
ATSINSmove(tmp22, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 564(line=27, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp22
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 578(line=27, offs=22) -- 582(line=27, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__2)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 593(line=28, offs=11) -- 598(line=28, offs=16)
*/
ATSINSmove(tmp23, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 590(line=28, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp23
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 604(line=28, offs=22) -- 608(line=28, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__3)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 619(line=29, offs=11) -- 624(line=29, offs=16)
*/
ATSINSmove(tmp24, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(4))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 616(line=29, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp24
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 630(line=29, offs=22) -- 634(line=29, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__4)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 645(line=30, offs=11) -- 650(line=30, offs=16)
*/
ATSINSmove(tmp25, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 642(line=30, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp25
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 656(line=30, offs=22) -- 660(line=30, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__5)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 671(line=31, offs=11) -- 676(line=31, offs=16)
*/
ATSINSmove(tmp26, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(6))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 668(line=31, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp26
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 682(line=31, offs=22) -- 686(line=31, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__6)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 697(line=32, offs=11) -- 702(line=32, offs=16)
*/
ATSINSmove(tmp27, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 694(line=32, offs=8) -- 722(line=33, offs=10)
*/
ATSif(
tmp27
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 708(line=32, offs=22) -- 712(line=32, offs=26)
*/
ATSINSmove(tmpret19, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__7)) ;
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 720(line=33, offs=8) -- 722(line=33, offs=10)
*/
ATSINSmove(tmpret19, PMVtmpltcstmat[0](g1int_neg<S2Eextkind(atstype_int)>)(ATSPMVi0nt(1))) ;

} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret19) ;
} /* end of [board_get_3] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 728(line=35, offs=5) -- 1473(line=56, offs=4)
*/
/*
local: 
global: board_set_4$0(level=0)
local: 
global: 
*/
ATSstatic()
postiats_tyrec_0
board_set_4(postiats_tyrec_0 arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret28, postiats_tyrec_0) ;
ATStmpdec(tmp29, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp30, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp31, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp32, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp33, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp34, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp35, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp36, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp37, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp38, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp39, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp40, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp41, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp42, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp43, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp44, atstkind_t0ype(atstype_bool)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 728(line=35, offs=5) -- 1473(line=56, offs=4)
*/
ATSINSflab(__patsflab_board_set_4):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 774(line=36, offs=37) -- 1473(line=56, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 785(line=37, offs=8) -- 787(line=37, offs=10)
*/
ATSINSmove(tmp29, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__0)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 789(line=37, offs=12) -- 791(line=37, offs=14)
*/
ATSINSmove(tmp30, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__1)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 793(line=37, offs=16) -- 795(line=37, offs=18)
*/
ATSINSmove(tmp31, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__2)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 797(line=37, offs=20) -- 799(line=37, offs=22)
*/
ATSINSmove(tmp32, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__3)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 801(line=37, offs=24) -- 803(line=37, offs=26)
*/
ATSINSmove(tmp33, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__4)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 805(line=37, offs=28) -- 807(line=37, offs=30)
*/
ATSINSmove(tmp34, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__5)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 809(line=37, offs=32) -- 811(line=37, offs=34)
*/
ATSINSmove(tmp35, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__6)) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 813(line=37, offs=36) -- 815(line=37, offs=38)
*/
ATSINSmove(tmp36, ATSSELfltrec(arg0, postiats_tyrec_0, atslab__7)) ;
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 830(line=39, offs=6) -- 835(line=39, offs=11)
*/
ATSINSmove(tmp37, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 827(line=39, offs=3) -- 1469(line=55, offs=14)
*/
ATSif(
tmp37
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 841(line=39, offs=17) -- 901(line=41, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 863(line=40, offs=19) -- 895(line=40, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 841(line=39, offs=17) -- 901(line=41, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 910(line=41, offs=15) -- 915(line=41, offs=20)
*/
ATSINSmove(tmp38, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 907(line=41, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp38
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 921(line=41, offs=26) -- 981(line=43, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 943(line=42, offs=19) -- 975(line=42, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 921(line=41, offs=26) -- 981(line=43, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 990(line=43, offs=15) -- 995(line=43, offs=20)
*/
ATSINSmove(tmp39, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(2))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 987(line=43, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp39
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1001(line=43, offs=26) -- 1061(line=45, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1023(line=44, offs=19) -- 1055(line=44, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1001(line=43, offs=26) -- 1061(line=45, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1070(line=45, offs=15) -- 1075(line=45, offs=20)
*/
ATSINSmove(tmp40, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(3))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1067(line=45, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp40
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1081(line=45, offs=26) -- 1141(line=47, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1103(line=46, offs=19) -- 1135(line=46, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1081(line=45, offs=26) -- 1141(line=47, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1150(line=47, offs=15) -- 1155(line=47, offs=20)
*/
ATSINSmove(tmp41, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(4))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1147(line=47, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp41
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1161(line=47, offs=26) -- 1221(line=49, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1183(line=48, offs=19) -- 1215(line=48, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1161(line=47, offs=26) -- 1221(line=49, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1230(line=49, offs=15) -- 1235(line=49, offs=20)
*/
ATSINSmove(tmp42, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(5))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1227(line=49, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp42
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1241(line=49, offs=26) -- 1301(line=51, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1263(line=50, offs=19) -- 1295(line=50, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1241(line=49, offs=26) -- 1301(line=51, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1310(line=51, offs=15) -- 1315(line=51, offs=20)
*/
ATSINSmove(tmp43, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(6))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1307(line=51, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp43
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1321(line=51, offs=26) -- 1381(line=53, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1343(line=52, offs=19) -- 1375(line=52, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, arg2) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, tmp36) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1321(line=51, offs=26) -- 1381(line=53, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1390(line=53, offs=15) -- 1395(line=53, offs=20)
*/
ATSINSmove(tmp44, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(7))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1387(line=53, offs=12) -- 1469(line=55, offs=14)
*/
ATSif(
tmp44
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1401(line=53, offs=26) -- 1461(line=55, offs=6)
*/
/*
letpush(beg)
*/
/* (*nothing*) */
/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1423(line=54, offs=19) -- 1455(line=54, offs=51)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__0, tmp29) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__1, tmp30) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__2, tmp31) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__3, tmp32) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__4, tmp33) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__5, tmp34) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__6, tmp35) ;
ATSINSstore_fltrec_ofs(tmpret28, postiats_tyrec_0, atslab__7, arg2) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1401(line=53, offs=26) -- 1461(line=55, offs=6)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1467(line=55, offs=12) -- 1469(line=55, offs=14)
*/
ATSINSmove(tmpret28, arg0) ;
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
} /* ATSendif */
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 774(line=36, offs=37) -- 1473(line=56, offs=4)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn(tmpret28) ;
} /* end of [board_set_4] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1479(line=58, offs=5) -- 1591(line=62, offs=50)
*/
/*
local: 
global: safety_test1_5$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
safety_test1_5(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(tmpret45, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp46, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp47, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp48, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp49, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp50, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1479(line=58, offs=5) -- 1591(line=62, offs=50)
*/
ATSINSflab(__patsflab_safety_test1_5):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmp46, PMVtmpltcstmat[0](neq_g0int_int<S2Eextkind(atstype_int)>)(arg1, arg3)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSif(
tmp46
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmp48, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg0, arg2)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmp47, PMVtmpltcstmat[0](g0int_abs<S2Eextkind(atstype_int)>)(tmp48)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmp50, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg1, arg3)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmp49, PMVtmpltcstmat[0](g0int_abs<S2Eextkind(atstype_int)>)(tmp50)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmpret45, PMVtmpltcstmat[0](neq_g0int_int<S2Eextkind(atstype_int)>)(tmp47, tmp49)) ;

} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1544(line=62, offs=3) -- 1591(line=62, offs=50)
*/
ATSINSmove(tmpret45, ATSPMVbool_false()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret45) ;
} /* end of [safety_test1_5] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1597(line=64, offs=5) -- 1792(line=71, offs=12)
*/
/*
local: board_get_3$0(level=0), safety_test1_5$0(level=0), safety_test2_6$0(level=0)
global: board_get_3$0(level=0), safety_test1_5$0(level=0), safety_test2_6$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_bool)
safety_test2_6(atstkind_t0ype(atstype_int) arg0, atstkind_t0ype(atstype_int) arg1, postiats_tyrec_0 arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, postiats_tyrec_0) ;
ATStmpdec(apy3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret51, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp52, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp53, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp54, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp55, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1597(line=64, offs=5) -- 1792(line=71, offs=12)
*/
ATSINSflab(__patsflab_safety_test2_6):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1665(line=68, offs=6) -- 1671(line=68, offs=12)
*/
ATSINSmove(tmp52, PMVtmpltcstmat[0](gte_g0int_int<S2Eextkind(atstype_int)>)(arg3, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1662(line=68, offs=3) -- 1792(line=71, offs=12)
*/
ATSif(
tmp52
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1709(line=69, offs=33) -- 1726(line=69, offs=50)
*/
ATSINSmove(tmp54, board_get_3(arg2, arg3)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1684(line=69, offs=8) -- 1727(line=69, offs=51)
*/
ATSINSmove(tmp53, safety_test1_5(arg0, arg1, arg3, tmp54)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1681(line=69, offs=5) -- 1780(line=70, offs=53)
*/
ATSif(
tmp53
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1765(line=70, offs=38) -- 1768(line=70, offs=41)
*/
ATSINSmove(tmp55, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg3, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1739(line=70, offs=12) -- 1769(line=70, offs=42)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, arg2) ;
ATSINSmove_tlcal(apy3, tmp55) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_safety_test2_6) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1775(line=70, offs=48) -- 1780(line=70, offs=53)
*/
ATSINSmove(tmpret51, ATSPMVbool_false()) ;
} /* ATSendif */
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1788(line=71, offs=8) -- 1792(line=71, offs=12)
*/
ATSINSmove(tmpret51, ATSPMVbool_true()) ;
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret51) ;
} /* end of [safety_test2_6] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1798(line=73, offs=5) -- 2374(line=103, offs=2)
*/
/*
local: print_board_2$0(level=0), board_get_3$0(level=0), board_set_4$0(level=0), safety_test2_6$0(level=0), search_7$0(level=0)
global: print_dots_0$0(level=0), print_row_1$0(level=0), print_board_2$0(level=0), board_get_3$0(level=0), board_set_4$0(level=0), safety_test1_5$0(level=0), safety_test2_6$0(level=0), search_7$0(level=0)
local: 
global: 
*/
ATSstatic()
atstkind_t0ype(atstype_int)
search_7(postiats_tyrec_0 arg0, atstkind_t0ype(atstype_int) arg1, atstkind_t0ype(atstype_int) arg2, atstkind_t0ype(atstype_int) arg3)
{
/* tmpvardeclst(beg) */
ATStmpdec(apy0, postiats_tyrec_0) ;
ATStmpdec(apy1, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy2, atstkind_t0ype(atstype_int)) ;
ATStmpdec(apy3, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmpret56, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp57, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp58, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp59, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp60, postiats_tyrec_0) ;
ATStmpdec(tmp61, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp62, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp63) ;
// ATStmpdec_void(tmp64) ;
ATStmpdec(tmp65, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp66) ;
// ATStmpdec_void(tmp67) ;
ATStmpdec(tmp68, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp69, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp70, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp71, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp72, atstkind_t0ype(atstype_bool)) ;
ATStmpdec(tmp73, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp74, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp75, atstkind_t0ype(atstype_int)) ;
ATStmpdec(tmp76, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1798(line=73, offs=5) -- 2374(line=103, offs=2)
*/
ATSINSflab(__patsflab_search_7):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1860(line=78, offs=1) -- 1865(line=78, offs=6)
*/
ATSINSmove(tmp57, PMVtmpltcstmat[0](lt_g0int_int<S2Eextkind(atstype_int)>)(arg2, ATSPMVintrep(8))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1857(line=77, offs=1) -- 2372(line=102, offs=2)
*/
ATSif(
tmp57
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1871(line=79, offs=6) -- 2285(line=98, offs=4)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1912(line=80, offs=38) -- 1915(line=80, offs=41)
*/
ATSINSmove(tmp59, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1888(line=80, offs=14) -- 1916(line=80, offs=42)
*/
ATSINSmove(tmp58, safety_test2_6(arg1, arg2, arg0, tmp59)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1922(line=82, offs=3) -- 2281(line=97, offs=35)
*/
ATSif(
tmp58
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1939(line=83, offs=10) -- 2246(line=96, offs=8)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1959(line=84, offs=17) -- 1979(line=84, offs=37)
*/
ATSINSmove(tmp60, board_set_4(arg0, arg1, arg2)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1996(line=86, offs=10) -- 1999(line=86, offs=13)
*/
ATSINSmove(tmp62, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1996(line=86, offs=10) -- 2003(line=86, offs=17)
*/
ATSINSmove(tmp61, PMVtmpltcstmat[0](eq_g0int_int<S2Eextkind(atstype_int)>)(tmp62, ATSPMVintrep(8))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1993(line=86, offs=7) -- 2238(line=95, offs=10)
*/
ATSif(
tmp61
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2017(line=87, offs=14) -- 2176(line=92, offs=12)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2040(line=88, offs=20) -- 2078(line=88, offs=58)
*/
ATSINSmove_void(tmp63, atspre_print_string(ATSPMVstring("Solution #"))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2062(line=88, offs=42) -- 2068(line=88, offs=48)
*/
ATSINSmove(tmp65, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg3, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2040(line=88, offs=20) -- 2078(line=88, offs=58)
*/
ATSINSmove_void(tmp64, atspre_print_int(tmp65)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2040(line=88, offs=20) -- 2078(line=88, offs=58)
*/
ATSINSmove_void(tmp66, atspre_print_string(ATSPMVstring(":\n\n"))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2098(line=89, offs=20) -- 2114(line=89, offs=36)
*/
ATSINSmove_void(tmp67, print_board_2(tmp60)) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2152(line=91, offs=26) -- 2155(line=91, offs=29)
*/
ATSINSmove(tmp68, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2157(line=91, offs=31) -- 2163(line=91, offs=37)
*/
ATSINSmove(tmp69, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg3, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2137(line=91, offs=11) -- 2164(line=91, offs=38)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp68) ;
ATSINSmove_tlcal(apy3, tmp69) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_search_7) ;
ATStailcal_end()

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2017(line=87, offs=14) -- 2176(line=92, offs=12)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2215(line=94, offs=24) -- 2218(line=94, offs=27)
*/
ATSINSmove(tmp70, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2202(line=94, offs=11) -- 2228(line=94, offs=37)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, tmp60) ;
ATSINSmove_tlcal(apy1, tmp70) ;
ATSINSmove_tlcal(apy2, ATSPMVi0nt(0)) ;
ATSINSmove_tlcal(apy3, arg3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_search_7) ;
ATStailcal_end()

} /* ATSendif */
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1939(line=83, offs=10) -- 2246(line=96, offs=8)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2271(line=97, offs=25) -- 2274(line=97, offs=28)
*/
ATSINSmove(tmp71, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(arg2, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2256(line=97, offs=10) -- 2281(line=97, offs=35)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, arg1) ;
ATSINSmove_tlcal(apy2, tmp71) ;
ATSINSmove_tlcal(apy3, arg3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_search_7) ;
ATStailcal_end()

} /* ATSendif */
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 1871(line=79, offs=6) -- 2285(line=98, offs=4)
*/
/*
INSletpop()
*/
} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2298(line=100, offs=6) -- 2303(line=100, offs=11)
*/
ATSINSmove(tmp72, PMVtmpltcstmat[0](gt_g0int_int<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(0))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2295(line=100, offs=3) -- 2370(line=101, offs=67)
*/
ATSif(
tmp72
) ATSthen() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2325(line=101, offs=22) -- 2328(line=101, offs=25)
*/
ATSINSmove(tmp73, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2345(line=101, offs=42) -- 2348(line=101, offs=45)
*/
ATSINSmove(tmp76, PMVtmpltcstmat[0](g0int_sub<S2Eextkind(atstype_int)>)(arg1, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2330(line=101, offs=27) -- 2349(line=101, offs=46)
*/
ATSINSmove(tmp75, board_get_3(arg0, tmp76)) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2330(line=101, offs=27) -- 2353(line=101, offs=50)
*/
ATSINSmove(tmp74, PMVtmpltcstmat[0](g0int_add<S2Eextkind(atstype_int)>)(tmp75, ATSPMVi0nt(1))) ;

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2313(line=101, offs=10) -- 2360(line=101, offs=57)
*/
ATStailcal_beg()
ATSINSmove_tlcal(apy0, arg0) ;
ATSINSmove_tlcal(apy1, tmp73) ;
ATSINSmove_tlcal(apy2, tmp74) ;
ATSINSmove_tlcal(apy3, arg3) ;
ATSINSargmove_tlcal(arg0, apy0) ;
ATSINSargmove_tlcal(arg1, apy1) ;
ATSINSargmove_tlcal(arg2, apy2) ;
ATSINSargmove_tlcal(arg3, apy3) ;
ATSINSfgoto(__patsflab_search_7) ;
ATStailcal_end()

} ATSelse() {
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2366(line=101, offs=63) -- 2370(line=101, offs=67)
*/
ATSINSmove(tmpret56, arg3) ;
} /* ATSendif */
} /* ATSendif */
ATSfunbody_end()
ATSreturn(tmpret56) ;
} /* end of [search_7] */

/*
/Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2392(line=105, offs=17) -- 2462(line=108, offs=2)
*/
/*
local: search_7$0(level=0)
global: print_dots_0$0(level=0), print_row_1$0(level=0), print_board_2$0(level=0), board_get_3$0(level=0), board_set_4$0(level=0), safety_test1_5$0(level=0), safety_test2_6$0(level=0), search_7$0(level=0), mainats_0_void$8$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret77) ;
ATStmpdec(tmp78, postiats_tyrec_0) ;
ATStmpdec(tmp79, atstkind_t0ype(atstype_int)) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2386(line=105, offs=11) -- 2462(line=108, offs=2)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2397(line=105, offs=22) -- 2462(line=108, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2411(line=106, offs=13) -- 2428(line=106, offs=30)
*/
ATSINSmove_fltrec_beg()
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__0, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__1, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__2, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__3, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__4, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__5, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__6, ATSPMVi0nt(0)) ;
ATSINSstore_fltrec_ofs(tmp78, postiats_tyrec_0, atslab__7, ATSPMVi0nt(0)) ;
ATSINSmove_fltrec_end()
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2439(line=107, offs=11) -- 2460(line=107, offs=32)
*/
ATSINSmove(tmp79, search_7(tmp78, ATSPMVi0nt(0), ATSPMVi0nt(0), ATSPMVi0nt(0))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2397(line=105, offs=22) -- 2462(line=108, offs=2)
*/
ATSINSmove_void(tmpret77, ATSPMVempty()) ;
/*
emit_instr: loc0 = /Users/davidfeng/Desktop/Edu/BU/5Se26F/CS413/CS413-2026-Fall/CS413-2026-Fall-DaveF/assigns/01/MySolution/eight_queens.dats: 2397(line=105, offs=22) -- 2462(line=108, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret77) ;
} /* end of [mainats_0_void] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_davidfeng_057_Desktop_057_Edu_057_BU_057_5Se26F_057_CS413_057_CS413_055_2026_055_Fall_057_CS413_055_2026_055_Fall_055_DaveF_057_assigns_057_01_057_MySolution_057_eight_queens_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
